# Generated by Django 4.0.3 on 2023-05-09 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Altitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='AtmosphericVariables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=8)),
                ('density', models.DecimalField(decimal_places=2, max_digits=8)),
                ('altitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.altitude')),
            ],
        ),
    ]
